on:
  push:
    branches: [ main ]
jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: MohammedCh/kongAction@main
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install inso
        run: npm install -g insomnia-inso
      - name: Lint
        run: inso lint spec "swagger.json" --ci
      # - name: Run test suites
      #   run: inso run test "swagger.json" --env UnitTest --ci
      - name: Generate declarative config
        run: inso generate config "swagger.json" --type declarative | tee kong.yml
      - name: print file
        run: cat kong.yml
